name: wmt14.de-en
source_lang: en
target_lang: de

# Path must be synchronized with prepare_wmt14_deen.sh result
path:
    source_train: dataset/${name}.train.norm.${source_lang}
    source_dev: dataset/${name}.dev.norm.${source_lang}
    source_test: dataset/${name}.test.norm.${source_lang}
    target_train: dataset/${name}.train.norm.${target_lang}
    target_dev: dataset/${name}.dev.norm.${target_lang}
    target_test: dataset/${name}.test.norm.${target_lang}
