name: wmt14.example
source_lang: en
target_lang: de

# Drop variable interpolation due to omegaconf issue  (ref: https://github.com/omry/omegaconf/issues/369)
path:
    source_train: dataset/wmt14.example.train.norm.en
    source_dev: dataset/wmt14.example.dev.norm.en
    source_test: dataset/wmt14.example.test.norm.en
    target_train: dataset/wmt14.example.train.norm.de
    target_dev: dataset/wmt14.example.dev.norm.de
    target_test: dataset/wmt14.example.test.norm.de
